### ISSUE TITLE
Healthcheck fails on all nodes due to IBC-Go module not found

### ISSUE THREAD

**Issue by freak12techno** [informalsystems/hermes#3880]
## Summary of Bug

On Hermes startup (or on invoking `hermes health-check` manually), it spawns a lot of messages on all of the chains I have in config that the healthcheck failed for this chain because it allegedly doesn't have IBC-Go module (although it's not true), for example on Cosmos Hub:

```
Mar 11 17:24:18 monitoring-logging hermes[925785]: 2024-03-11T16:24:18.679278Z  WARN ThreadId(22) 
health_check{chain=cosmoshub-4}: reason: compatibility check failed for chain 'cosmoshub-4' at
'http://rpc.cosmos.quokkastake.io:9090/': IBC-Go module version not found, required >=4.1.1, <9
```

If you go into REST's /node_info (example on my node: https://api.cosmos.quokkastake.io/node_info), it'll show there's ibc-go dependency in build_deps:

```
24	"github.com/cosmos/ibc-go/v4@v4.4.2"
```

although it's not processed correctly.
I am not sure yet why this keeps happening, wonder if it might happen because the dependency itself has the `v4` suffix here?

This doesn't seem to affect anything, yet having more warning messages that are misleading is somewhat annoying.

## Version

v1.8.1

## Steps to Reproduce

Run `hermes health-check` or restart Hermes.

## Acceptance Criteria

???

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
@freak12techno Thanks for reporting this! The issue should be fixed in Hermes v1.8.2 if you want to give it a try

**Comment by freak12techno** [comment]
@romac already did, and yeah, it fixed it, thanks!
(I still have some other issues, will likely report it separately, but this one seems to be gone)
